name: Deploy to AWS S3 
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 

    - name: setup node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '22' 
    
    - name: npm install
      working-directory: .
      run: npm install

    - name: npm build
      working-directory: .
      run: npm run build
    
    - name: setup aws cli
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: "ap-northeast-2"

    - name: deploy to s3
      run: |
        aws s3 cp ./dist s3://www.jooncodehyuk.site/ --recursive
        
    - name: invalidate cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id E2GV49Q9PL9CXW --paths "/*"